USE registrar;

INSERT INTO department VALUES ('1', 'Biology', '832040');
INSERT INTO department VALUES ('2', 'Mathematical Sciences', '65536');
INSERT INTO department VALUES ('3', 'Physics', '299792458');
INSERT INTO instructor VALUES ('1', 'Lovelace', '65536', '2');
INSERT INTO instructor VALUES ('2', 'Knuth', '32768', '2');
INSERT INTO instructor VALUES ('3', 'Curie', '12906', '3');
INSERT INTO instructor VALUES ('4', 'Goodall', '4181', '1');
INSERT INTO instructor VALUES ('5', 'Darwin', '2584', '1');
INSERT INTO instructor VALUES ('6', 'Dirac', '9192', '3');
INSERT INTO student VALUES ('1', 'Alex', '64', '2');
INSERT INTO student VALUES ('2', 'Kim', '95', '5');
INSERT INTO student VALUES ('3', 'Chris', '0', NULL);
INSERT INTO student VALUES ('4', 'Stacey', '14', '5');
INSERT INTO student VALUES ('5', 'Jordan', '129', '1');
INSERT INTO student VALUES ('6', 'Kelly', '114', '2');
INSERT INTO student VALUES ('7', 'Chris', '33', '3');
INSERT INTO student VALUES ('8', 'Ryan', '26', NULL);
INSERT INTO student VALUES ('9', 'Robin', '98', '5');
INSERT INTO student VALUES ('10', 'Jessie', '44', '5');
INSERT INTO course VALUES('1', 'Physics I: Motion');
INSERT INTO course VALUES('2', 'Physics II: Waves and Matter');
INSERT INTO course VALUES('3', 'Physics III: Electromagnetism');
INSERT INTO course VALUES('4', 'Biological Core Concepts: Systems');
INSERT INTO course VALUES('5', 'Biological Core Concepts: Mechanisms');
INSERT INTO course VALUES('6', 'Computer Science I');
INSERT INTO course VALUES('7', 'Computer Science II');
INSERT INTO course VALUES('8', 'Databases');
INSERT INTO course VALUES('9', 'Cybersecurity');
INSERT INTO instructor_teaches_course VALUES('1', '6');
INSERT INTO instructor_teaches_course VALUES('1', '7');
INSERT INTO instructor_teaches_course VALUES('1', '9');
INSERT INTO instructor_teaches_course VALUES('2', '7');
INSERT INTO instructor_teaches_course VALUES('2', '8');
INSERT INTO instructor_teaches_course VALUES('3', '2');
INSERT INTO instructor_teaches_course VALUES('3', '3');
INSERT INTO instructor_teaches_course VALUES('4', '4');
INSERT INTO instructor_teaches_course VALUES('5', '5');
INSERT INTO instructor_teaches_course VALUES('6', '1');
INSERT INTO instructor_teaches_course VALUES('6', '3');
INSERT INTO student_takes_course VALUES('1', '4');
INSERT INTO student_takes_course VALUES('4', '4');
INSERT INTO student_takes_course VALUES('6', '4');
INSERT INTO student_takes_course VALUES('7', '4');
INSERT INTO student_takes_course VALUES('1', '5');
INSERT INTO student_takes_course VALUES('10', '1');
INSERT INTO student_takes_course VALUES('6', '1');
INSERT INTO student_takes_course VALUES('5', '1');
INSERT INTO student_takes_course VALUES('2', '2');
INSERT INTO student_takes_course VALUES('9', '2');
INSERT INTO student_takes_course VALUES('3', '2');
INSERT INTO student_takes_course VALUES('6', '3');
INSERT INTO student_takes_course VALUES('9', '3');
INSERT INTO student_takes_course VALUES('2', '3');
INSERT INTO student_takes_course VALUES('10', '5');
INSERT INTO student_takes_course VALUES('3', '5');
INSERT INTO student_takes_course VALUES('9', '8');
INSERT INTO student_takes_course VALUES('2', '8');
INSERT INTO student_takes_course VALUES('10', '8');
INSERT INTO student_takes_course VALUES('7', '8');
